3.21.1 LIVE.8892745 | Text Korrekturen
rjcncpt/StarCitizen-Deutsch-INI pull request #228
Opened 2023-11-24 23:52 UTC by rjcncpt

- Texte zur Waffenstillstandszone überarbeitet
- Eigennamen von Gesteinen zurückgeführt
- Texte in shop_ui_transactionResult_ überarbeitet

2023-11-24 23:55 UTC, rjcncpt commented
@greluc @MaxM1211 könnt ihr im Spiel an den Verkaufsterminals mal schauen was bei der Seitennavigation angezeigt wird? Ursprünglich sollte "Erste" und "Letzte" da stehen. Ich habe  für einen Test mal ⏪ und ⏩ Symbole verwendet.

2023-11-25 00:18 UTC, rjcncpt commented on live/global.ini
> +shop_ui_CommodityKiosk_Demand_Medium=Mittleres Lagerbestand
Mittlerer. Ändere ich morgen

2023-11-25 00:19 UTC, rjcncpt commented on live/global.ini
> +shop_ui_CommodityKiosk_OwnedByPartyMembers,P=Im Besitz von Gruppenmitglied/ern
Partymitglied.

2023-11-25 00:20 UTC, rjcncpt commented on live/global.ini
> +shop_ui_CommodityKiosk_UnregisteredItem=Nicht registriertes Element
Gegenstand

2023-11-25 01:56 UTC, MaxM1211 commented
> @greluc @MaxM1211 könnt ihr im Spiel an den Verkaufsterminals mal schauen was bei der Seitennavigation angezeigt wird? Ursprünglich sollte "Erste" und "Letzte" da stehen. Ich habe für einen Test mal ⏪ und ⏩ Symbole verwendet.

Klappt leider nicht (siehe Discord)

2023-11-25 02:07 UTC, MaxM1211 requested changes

2023-11-25 02:07 UTC, MaxM1211 commented on live/global.ini
> +hud_mining_rock_name_8=Atacamite Vorkommen
\- Fehlt

2023-11-25 02:07 UTC, MaxM1211 commented on live/global.ini
> +shop_ui_InsufficientFundsMsg=Du verfügst nicht über ausreichende Geld für diesen Kauf.
ausreichend

2023-11-25 02:07 UTC, MaxM1211 commented on live/global.ini
> +shop_ui_pageNavigation_negative_firstpage=⏪
Zurück ändern

2023-11-25 10:22 UTC, MaxM1211 approved these changes

2023-11-25 10:56 UTC, merged