3.22.0 LIVE.9003408 | Polishing
rjcncpt/StarCitizen-Deutsch-INI pull request #411
Opened 2024-01-09 16:42 UTC by rjcncpt

Grundlegende Korrekturen in der Übersetzung, Locations und Verknüpfungen zw. ~mission(location) und der Auftragsbeschreibung. Da ist noch polishing notwendig. @MaxM1211 hat dazu von mir eine Aufgabe erhalten die er gern verteilen kann. Ist ganz schön kniffelig.

2024-01-10 22:25 UTC, MaxM1211 requested changes

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +recoverstolen_space_desc_0003=Kleines Wunder. Einigen guten Leuten an ~mission(Destination) wurde ein ~mission(Contractor|RecoveryItem) gestohlen, aber wir konnten es tatsächlich aufspüren. Es stellt
```suggestion
recoverstolen_space_desc_0003=Kleines Wunder. Einigen guten Leuten an ~mission(destination) wurde ein ~mission(Contractor|RecoveryItem) gestohlen, aber wir konnten es tatsächlich aufspüren. Es stellt sich heraus, dass ein Schurke namens ~mission(TargetName) die gestohlene ~mission(Contractor|RecoveryItem) gerade an Bord seines Schiffes hat. Ein erfahrener Betreiber sollte jedoch in der Lage sein, sein Schiff aufzuspüren und das Eigentum dorthin zurückzubringen, wo es hingehört. ~mission(Contractor|RecoveryTimed) ~mission(Danger)
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +recoverstolen_space_desc_0006=Habe heute eine Pause. Nachdem einer unserer Kunden an ~mission(Destination) ausgeraubt wurde, konnten wir seine gestohlene ~mission(Contractor|RecoveryItem) bis zum Sch
```suggestion
recoverstolen_space_desc_0006=Habe heute eine Pause. Nachdem einer unserer Kunden an ~mission(destination) ausgeraubt wurde, konnten wir seine gestohlene ~mission(Contractor|RecoveryItem) bis zum Schiff einer ~mission(TargetName) zurückverfolgen. Wir hoffen, dass wir mit Ihrer Hilfe den Täter ausfindig machen und das Eigentum unversehrt zurückerhalten können. ~mission(Contractor|RecoveryTimed) ~mission(Danger)
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +searchbody_obj_long_01=Suche ~mission(TargetName): ~mission(Location).
```suggestion
searchbody_obj_long_01=Suche ~mission(TargetName) bei ~mission(Location).
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +searchcrew_obj_long_01=Finde die vermisste Crew: ~mission(Location).
```suggestion
searchcrew_obj_long_01=Finde die vermisste Crew bei ~mission(Location).
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +shuttle_at=Shuttle an
Theoretisch kein Leerzeichen am ende

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +shuttle_is_at_location=zum Shuttle-Standort
Warum zum?

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacecargo_illegal_desc_0002=Ich habe Wind davon bekommen, dass eine Lieferung von ~mission(Item), auf die der ~mission(Client) scharf war, auf einer ~mission(Ship) aufgetaucht ist, das auf dem Weg a
```suggestion
spacecargo_illegal_desc_0002=Ich habe Wind davon bekommen, dass eine Lieferung von ~mission(Item), auf die der ~mission(Client) scharf war, auf einer ~mission(Ship) aufgetaucht ist, die auf dem Weg aus dem System war. Glücklicherweise sind sie nicht allzu weit gekommen. Alles, was noch bleibt, ist, dass jemand die Waren von ~mission(Location) holt und sie am ~mission(Destination) absetzt. ~mission(Timed)~mission(Danger)
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacecargo_legal_desc_0004=~mission(Contractor) sucht einen freiberuflichen Piloten für einen Bergungsjob. Eine ~mission(Ship) ging während des Transports verloren, daher werden Sie beauftragt, zu ~m
```suggestion
spacecargo_legal_desc_0004=~mission(Contractor) sucht einen freiberuflichen Piloten für einen Bergungsjob. Eine ~mission(Ship) ging während des Transports verloren, daher werden Sie beauftragt, zu ~mission(Location|Address) zu navigieren und eine Kiste ~mission(Item) aus den Trümmern zu bergen. Anschließend müssen Sie die Sendung zu ~mission(Destination) liefern. Die Zahlung erfolgt bei Zustellung.\n\n~mission(Timed)\n\n~mission(Danger)
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacesteal_desc_0002=Benötigen Sie jemanden, der für die ~mission(Contractor|Name) ein wenig aggressive Akquise durchführt. Sie haben sich auf eine bestimmte ~mission(Contractor|StealItem) konzentrie
```suggestion
spacesteal_desc_0002=Benötigen Sie jemanden, der für die ~mission(Contractor|Name) ein wenig aggressive Akquise durchführt. Sie haben sich auf eine bestimmte ~mission(Contractor|StealItem) konzentriert und wissen Sie was? Es wird hübsch an Bord eines Glückspilzschiffs sein. Alles, was Sie tun müssen, ist, ~mission(TargetName) einen Besuch abzustatten, sich die Waren zu schnappen und sie zu ~mission(destination) zu fliegen. ~mission(Contractor|StealTimed) ~mission(Danger)Das ist es. Das Geld gehören grundsätzlich bereits Ihnen.
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacesteal_desc_0003=Ich habe ein paar Gerüchte gehört, dass ein Schiff mit wertvoller Fracht an Bord losfährt, aber dank mir und Ihnen wird das nicht lange so bleiben. Du wirst herausfinden, wo das
```suggestion
spacesteal_desc_0003=Ich habe ein paar Gerüchte gehört, dass ein Schiff mit wertvoller Fracht an Bord losfährt, aber dank mir und Ihnen wird das nicht lange so bleiben. Du wirst herausfinden, wo das Schiff von ~mission(TargetName) fliegt, und es von seiner Last befreien. ~mission(Danger) Sobald Sie es erhalten haben, geben Sie die ~mission(Contractor|StealItem) an ~mission(destination) ab und die ~mission(Contractor|Name) wird dafür sorgen, dass Sie für Ihre Bemühungen entlohnt werden. ~mission(Contractor|StealTimed)
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacesteal_desc_0004=Heute ist Zahltag! Die ~mission(Contractor|Name) möchte eine ~mission(Contractor|StealItem), den ~mission(TargetName) an Bord seines Schiffes hat und es liegt an dir, ihn für sie
```suggestion
spacesteal_desc_0004=Heute ist Zahltag! Die ~mission(Contractor|Name) möchte eine ~mission(Contractor|StealItem), den ~mission(TargetName) an Bord seines Schiffes hat und es liegt an dir, ihn für sie zu holen. Lassen Sie mich Ihnen sagen, Sie werden ein paar Scheine machen, wenn Sie derjenige sind, der es zu ~mission(destination) bringt. ~mission(Contractor|StealTimed) ~mission(Danger)\n\nEine letzte Sache noch: Ich müsste das gar nicht sagen, aber wenn Sie auch nur daran denken, die Ware für sich zu behalten, müssen Sie sich darüber im Klaren sein, dass Sie nicht lange genug leben werden, um sie zu genießen.
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +spacesteal_desc_0006=Ich bin mir nicht sicher, ob du dich daran erinnerst, aber vor einiger Zeit hat ~mission(Contractor|StealNickname) diese erstaunliche Beute gesteigert, sie dann aber sofort wie e
```suggestion
spacesteal_desc_0006=Ich bin mir nicht sicher, ob du dich daran erinnerst, aber vor einiger Zeit hat ~mission(Contractor|StealNickname) diese erstaunliche Beute gesteigert, sie dann aber sofort wie ein Riesenidiot verloren. Nun, jeder und seine Großmutter haben danach gesucht, aber Ihre Großmutter hat es wirklich gefunden. Die ~mission(Contractor|StealItem) ist an Bord des Schiffes von jemandem namens ~mission(TargetName). Ich habe noch nie von ihnen gehört, aber wer auch immer sie sind, sie werden es bereuen, wenn sie auf diesen Vorrat stoßen. Die ~mission(Contractor|Name) zahlt uns einen Finderlohn, wenn wir es ergattern und zu ~mission(destination) bringen können. ~mission(Contractor|StealTimed) ~mission(Danger) Schaffen Sie es und wir werden beide Legenden sein.
```

2024-01-10 22:25 UTC, MaxM1211 commented on live/global.ini
> +vaughn_assassination_VH_desc_001=Gerade ist ein kniffliger Auftrag eingetroffen, für den Sie meiner Meinung nach ideal geeignet sind.\n\Erwarten Sie ~mission(TargetName) an Bord eines schwer bewaffne
```suggestion
vaughn_assassination_VH_desc_001=Gerade ist ein kniffliger Auftrag eingetroffen, für den Sie meiner Meinung nach ideal geeignet sind.\n\nErwarten Sie ~mission(TargetName) an Bord eines schwer bewaffneten Schiffes in der Nähe von ~mission(Location|Address) in Begleitung von einigen der besten Piloten, die man anheuern kann, zu treffen.\n\nBehandeln Sie die Begleiter wie es Ihnen beliebt. Solange Sie ~mission(TargetName) töten, werde ich mehr als zufrieden sein.\n\nMit Respekt,\nVaughn\n
```

2024-01-10 22:36 UTC, rjcncpt commented on live/global.ini
> +Frontend_PU_Version=3.22.0 - Vom Schrotthändler zum Millionär\nCommunity Übersetzung. Keine offizielle CIG Übersetung\n\n
Um eine Lücke rein zu bekommen. Weißt doch, Text braucht Luft zum atmen xD

2024-01-10 22:40 UTC, rjcncpt commented on live/global.ini
> +MissionManager_CryAstroCrime_1_Title_Short=Eliminate A Problem
Gute Frage. Muss man wohl im Spiel sehen

2024-01-10 22:40 UTC, MaxM1211 commented on live/global.ini
> +Frontend_PU_Version=3.22.0 - Vom Schrotthändler zum Millionär\nCommunity Übersetzung. Keine offizielle CIG Übersetung\n\n
Achso, habs grad angeschaut :-D Ich dachte darunter steht nichts

2024-01-10 22:41 UTC, rjcncpt commented on live/global.ini
> +Frontend_PU_Version=3.22.0 - Vom Schrotthändler zum Millionär\nCommunity Übersetzung. Keine offizielle CIG Übersetung\n\n
^^

2024-01-10 22:50 UTC, rjcncpt commented on live/global.ini
> +mg_ruto_sectorsweep_danger_001=Und ich weiß nicht, ob sie ein spezielles Training absolviert haben oder ob sie das Futter für die Bastarde geändert haben, aber einige dieser Sicherheitspiloten sind g
Klingt zumindest nicht so dumm ^^

2024-01-10 22:52 UTC, rjcncpt commented on live/global.ini
> +planetcollect_oresamp_location_0001=Einrichtung auf Daymar
jo da bin ich noch nicht. Bekommt ja ein neues Layout

2024-01-11 21:38 UTC, MaxM1211 approved these changes
Sah ganz gut aus 
Bis auf die Placeholder natürlich

2024-01-11 21:39 UTC, merged