3.22.1-LIVE.9097523 | crusader_
rjcncpt/StarCitizen-Deutsch-INI pull request #469
Opened 2024-02-14 14:47 UTC by greluc

crusader_ part 1

#405

2024-02-14 22:27 UTC, rjcncpt commented
Moin. Ich würde formell verwenden für die Reputationstexte. @MaxM1211 wie siehst du das?

2024-02-14 22:41 UTC, MaxM1211 commented
Sehe ich ähnlich,  jedoch würde ich dass von der Fraktion abhängig machen. Ist es eher ein Unternehmen -> formell, ist es eine Gruppe Rebellen eher informell

2024-02-14 23:18 UTC, rjcncpt commented
> Sehe ich ähnlich, jedoch würde ich dass von der Fraktion abhängig machen. Ist es eher ein Unternehmen -> formell, ist es eine Gruppe Rebellen eher informell

Finde ich gut

2024-03-23 17:13 UTC, MaxM1211 requested changes

2024-03-23 17:13 UTC, MaxM1211 commented on live/global.ini
> +crusader_retakelocation_kareah_desc_001=Security Post Kareah wird von einer unbekannten Anzahl von Angreifern angegriffen.\n\nCrusader sucht Auftragnehmer, die schnell zur Station reisen und alle Ein
```suggestion
crusader_retakelocation_kareah_desc_001=Security Post Kareah wird von einer unbekannten Anzahl von Angreifern angegriffen.\n\nCrusader sucht Auftragnehmer, die schnell zur Station reisen und alle Eindringlinge in der Nähe töten, bevor unsere Sicherheitskräfte überwältigt werden.\n\nWir sind uns nicht sicher, ob die Angreifer das Schmuggelgut in unserem Beweislager oder unsere CrimeStat-Datenbank ins Visier nehmen, aber egal, was sie wollen, es muss unterbunden werden. Sie erhalten einen Kampfbonus für jedes eliminierte Ziel.\n\nMit der Annahme dieses Auftrags stimmen Sie allen Sicherheitsprotokollen von Crusader zu: Wenn Sie während Ihres Aufenthalts auf der Station Wachen oder andere autorisierte Auftragnehmer verletzen, wird Ihr Auftrag beendet, und Sie werden als Ziel markiert.\n\nDie Zeit drängt, aber stellen Sie sicher, dass Sie gut ausgerüstet sind, um die Feinde zu bewältigen, bevor Sie reagieren.\n\nAUFTRAG AUTORISIERT DURCH:\nKontaktoffizier Bautista\nID# 948J030K
```

2024-03-23 17:13 UTC, MaxM1211 commented on live/global.ini
> +crusader_sectorsweep_desc_005=Wir haben Probleme mit den ~mission(Client) in der Nähe bei ~mission(Location|Address). Sie benehmen sich, als ob ihnen der Ort gehört. Sie werden ihnen zeigen, dass dem
```suggestion
crusader_sectorsweep_desc_005=Wir haben Probleme mit den ~mission(Client) in der Nähe bei ~mission(Location|Address). Sie benehmen sich, als ob ihnen der Ort gehört. Sie werden ihnen zeigen, dass dem nicht so ist.\n\nBegeben Sie sich dorthin und vertreiben Sie sie aus dem Sektor.\n\n~mission(Danger)~mission(Timed)\n\nAUFTRAG AUTORISIERT DURCH:\nKontaktoffizier Gibbs\nID# 91G66BW0
```

2024-03-23 17:41 UTC, MaxM1211 requested changes
Sorry, hab nicht alle einzeln markiert gehabt :-)

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_UGF_eliminateall_allies_desc_rehire=Herzlichen Glückwunsch! Crusader Security hat beschlossen, Ihnen eine weitere Chance als Sicherheitsunternehmer zu bieten. Mit ein wenig harter Arbeit und
Friendly Fire -> Eigenbeschuss

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_002=Da ich in der Vergangenheit mit ähnlichen Aufträgen zu tun hatte, würde ich Ihnen raten, so viel Feuerkraft mitzubringen, wie Sie aufbringen können. Hoffentlich brauchen Sie sie n
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_003=Ich sollte Sie warnen, dass es sehr wahrscheinlich ist, dass Sie auf bewaffneten Widerstand stoßen werden. Seien Sie bereit.
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_004=Da ich in der Vergangenheit mit ähnlichen Verträgen zu tun hatte, vermute ich, dass Sie nur auf leichten Widerstand stoßen werden. Bestenfalls ein Einzelpilot, schlimmstenfalls ei
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_006=Unsere besten Informationen deuten darauf hin, dass Sie hier mit moderaten Feindkräften rechnen müssen. Es handelt sich möglicherweise um ein kleines Schiff mit mehreren Besatzung
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_high_002=Denken Sie daran, dass es sich dabei nicht um irgendwelche niedrigstufigen Söldner handelt, mit denen Sie konfrontiert werden. Sie verfügen über beträchtliche Angriffsfähigke
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_danger_high_003=Seien Sie sich bewusst, dass dies kein einfacher Auftrag sein wird. Informationen zufolge hat die ~mission(Client) ihr Arsenal stark erweitert und wird Ihnen so ziemlich alle
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_timed_001=Bitte beachten Sie auch, dass es eine strenge Frist für die Fertigstellung Ihrer Arbeit gibt.
Leerzeichen am Ende

2024-03-23 17:41 UTC, MaxM1211 commented on live/global.ini
> +crusader_timed_002=Denken Sie auch an die angegebene Frist. Wir müssen bis dahin alles erledigt haben.
Leerzeichen am Ende

2024-03-23 17:49 UTC, MaxM1211 approved these changes
LGTM 👍🏼

2024-03-23 17:50 UTC, merged