3.22.1-LIVE.9097523 | mg_miles_capturegang
rjcncpt/StarCitizen-Deutsch-INI pull request #538
Opened 2024-04-30 18:21 UTC by GeneralMine

Habe die `mg_miles_capturegang_` neuübersetzt und angepasst wie in #405 aufgelistet.

Klingt meiner Meinung nach viel besser. Ich hoffe es passt so und freue mich auf weitere Übersetzungen ;)

2024-04-30 19:06 UTC, MaxM1211 commented
Hey Marvin, danke dir. 

Wir/ich werden das nach dem Live Release von 3.23 prüfen, aber was ich bis jzt gesehen habe sah ganz gut aus :-)

Merci

2024-05-01 02:10 UTC, rjcncpt commented
> Habe die `mg_miles_capturegang_` neuübersetzt und angepasst wie in #405 aufgelistet.
> 
> Klingt meiner Meinung nach viel besser. Ich hoffe es passt so und freue mich auf weitere Übersetzungen ;)

Hey Marvin. Danke dir für die Korrektur :) Ich denke es lohnt nicht das jetzt noch zu übertragen. Ich habe deine Korrekturen lokal übernommen und wenn Max nichts auffälliges findet, geht es dann mit LIVE online :)

Danke!

2024-05-01 08:25 UTC, MaxM1211 requested changes
@rjcncpt Bitte einmal noch anpassen

@GeneralMine Danke dir für die Übersetzung. Sehr schön gemacht 👍🏼

2024-05-01 08:25 UTC, MaxM1211 commented on live/global.ini
> +mg_miles_capturegang_desc_006=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~mission
```suggestion
mg_miles_capturegang_desc_006=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~mission(Contractor|ApprovalCode)\n\nZUR SOFORTIGEN BEARBEITUNG\n\n**** *****\n__Hintergrundinformationen__\nEin Gruppenhaftbefehl wurde gegen die berüchtigte Schiffsdiebstahlbande aus Arlington erlassen, nachdem sie kürzlich einen dreisten Diebstahlversuch einer Idris aus einer Reparaturwerft unternommen hatte. Während der Überfall gestoppt wurde, haben sich die Mitglieder der Gruppe weit zerstreut. Eckhart Security hat den Kopfgeldauftrag für die sofortige Gefangennahme aller hochrangigen Gangmitglieder erhalten: Maltrox Arlington, Kass Dent, Nicks Cantwell, Sam "Weepy" Arlington, Oslo Arlington und Les Arlington.\n******* **\n\nMaltrox Arlington hat sich in letzter Zeit zurückgehalten, aber wir glauben, dass er aus seinem Versteck herausgekommen ist. Eine Patrouille tankte gerade an einer Tankstelle, als eines ihrer Schiffe gestohlen wurde. Maltrox ist der wahrscheinlichste Verdächtige. Während das Regtag vorübergehend deaktiviert war, konnten wir die Quantum-Signatur des Schiffes verfolgen und Ihnen diese Koordinaten zur Verfügung stellen.\n\nAls kriminelle Organisation in der dritten Generation steht die Arlington-Gang seit sechs Jahren unter der Führung von Maltrox. Seien Sie sich bewusst, dass dies ein kluges, aggressives und sehr gefährliches Ziel ist. Je mehr Ressourcen Sie einsetzen können, desto wahrscheinlicher ist es, dass wir Maltrox ein für alle Mal zu Fall bringen können.\n\nSie sind berechtigt, jede erforderliche Gewalt anzuwenden, um das Ziel auszuschalten.\n\nDie Zahlung erfolgt nach erfolgreichem Auftragsabschluss.\n\nDieser Auftrag ist nicht verhandelbar.\n\nDiese Nachricht kann vertrauliche, geschützte, privilegierte und/oder private Informationen enthalten. Die Informationen sind für die Nutzung durch die oben genannte natürliche oder juristische Person bestimmt.
```

Kleiner Logikfehler: Maltrox sollte der Gegner sein, unten stand `wir Maltrox ein für alle Mal zum Erfolg führen können`. Der Fehler kommt aber von uns :-)

2024-05-01 08:25 UTC, MaxM1211 commented on live/global.ini
> +mg_miles_capturegang_desc_idris=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~missi
```suggestion
mg_miles_capturegang_desc_idris=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~mission(Contractor|ApprovalCode)\n\nZUR SOFORTIGEN BEARBEITUNG\n\nEs scheint, als wäre der zweite Versuch für die Arlington-Bande von Erfolg gekrönt. Nach einem gescheiterten Versuch ist es der kürzlich entflohenen Verbrecherfamilie gelungen, eine Idris aus einem Reparaturhof zu stehlen. Jetzt wissen wir, wozu der Bergbaulaser und die biometrischen Daten dienten, die sie gestohlen haben.\n\nDa es uns beim ersten Mal so gut gelungen ist, sie zu fangen, wurde Eckhart Security die Vollstreckung des Haftbefehls gegen die Bande zugewiesen. Es wird beträchtliche Feuerkraft erfordern, um ein Großkampfschiff dieser Klasse abzuschießen.\n\nSie sind berechtigt, jede erforderliche Gewalt einzusetzen, um die Idris aufzuspüren und die Bande auszuschalten.\n\nDie Zahlung erfolgt nach erfolgreichem Abschluss des Auftrags und wird auf der Grundlage einer Bewertung der Kampfeffizienz von Ihnen und Ihrem Team angepasst.\n\nDieser Auftrag ist nicht verhandelbar.\n\nDiese Nachricht kann vertrauliche, geschützte, privilegierte und/oder private Informationen enthalten. Die Informationen sind für die Nutzung durch die oben genannte natürliche oder juristische Person bestimmt.
```

Konsistenz: Es war immer die Gewalt und nicht die Kraft (geht auch wieder auf unser Konto)

2024-05-01 09:46 UTC, rjcncpt commented on live/global.ini
> +mg_miles_capturegang_desc_idris=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~missi
Findest du noch mehr dieser Konsiszentfehler?

2024-05-01 10:42 UTC, rjcncpt commented on live/global.ini
> +mg_miles_capturegang_desc_idris=ECKHART SECURITY, LLC.\nAUFTRÄGE & VERSAND\n----------------------------\n\nAUFTRAGSART: Gruppenhaftbefehl\nAUFTRAGNEHMERSTATUS: Unabhängig\nGenehmigungscode: = ~missi
Jo ich meinte ja, generell 🙈😁

2024-05-01 14:00 UTC, rjcncpt commented
> @rjcncpt Bitte einmal noch anpassen
> 
> @GeneralMine Danke dir für die Übersetzung. Sehr schön gemacht 👍🏼

✅

2024-05-06 13:41 UTC, closed without merging